#!/bin/bash

echo stay taxi: $STAY_TAXI

if [ "$STAY_TAXI" = "no" ] 
then
   # destino=" ${_SSH_USER}@$4 "
   destino=" -l $TAXI_USER $4 "
fi

if [ "$USE_TAXI" = "si" ] 
then
   taxi=" -l ${_SSH_USER} -t $TAXI_SERVER " 
   if [ "$destino" != "" ] 
   then
        destino=" ssh $destino "
   fi
else 
   destino=" -l ${_SSH_USER} $4 "
fi

if [ "$PROXY" = "si" ] 
then
  proxy="tsocks "
fi

## THE CONSOLE IMPLEMENTATION WAS REMOVED
## WE NEED A FLEXIBLE ONE, NOT HARDCODED

ssh="$proxy ssh $taxi $destino"

echo $ssh
read n
let x=$RANDOM%10
sleep $x

$ssh

